TRYING_TO_LOAD_RANDOM_DATASET Signal_160_D_0_constant_12_None_0.1_1280 data/ARTIFICIAL_DATA/160/Signal_160_D_0_constant_12_None_0.1_1280
LAOD_FAILED_TRYING_TO_GENERATE_RANDOM_DATASET Signal_160_D_0_constant_12_None_0.1_1280
GENERATING_RANDOM_DATASET Signal_160_D_0_constant_12_None_0.1_1280
TREND 0.0976270078546495 0.43037873274483895 0.20552675214328775
Traceback (most recent call last):
  File "/home/circleci/project/tests/bugs/test_random_exogenous.py", line 11, in <module>
    b1 = tsds.generate_random_TS(N = 160 , FREQ = 'D', seed = 0, trendtype = "constant", cycle_length = 12, transform = "None", sigma = 0.10, exog_count = 1280);
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/pyaf/Bench/TS_datasets.py", line 333, in generate_random_TS
    tsspec = generate_random_TS_real(N , FREQ, seed, trendtype, cycle_length, transform, sigma, exog_count, ar_order)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/pyaf/Bench/TS_datasets.py", line 391, in generate_random_TS_real
    df_train['Signal'] = apply_transform(pos_signal , transform)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/pyaf/Bench/TS_datasets.py", line 297, in apply_transform
    transformed = transformed.astype(np.float64)
                  ^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'astype'
