Traceback (most recent call last):
  File "/home/circleci/project/tests/bugs/issue_32/bug_test_ozone_heroku_1_ws.py", line 31, in <module>
    cont = test_heroku_pyaf_2(data);
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/circleci/project/tests/bugs/issue_32/bug_test_ozone_heroku_1_ws.py", line 16, in test_heroku_pyaf_2
    import json, urllib3
ModuleNotFoundError: No module named 'urllib3'
